version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      BUNDLE_PATH: /usr/local/bundle
      RAILS_ENV: 'development'
      TZ: Asia/Tokyo
    ports:
      - '3041:3000'
    stdin_open: true
    tty: true
    volumes:
      - .:/root/react_rails
      - bundle:/usr/local/bundle
  db:
    image: postgres:11
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  bundle:
    driver: local
  data:
    driver: local
