default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: react_rails_development
test:
  <<: *default
  database: react_rails_test
production:
  <<: *default
  database: react_rails_production
  username: react_rails
  password: <%= ENV['REACT_RAILS_DATABASE_PASSWORD'] %>
